### PR TITLE
Fix race condition for creating cloudevent client

### LINKED ISSUE #227: Several sources construct their CloudEvents client without thread safety
## Expected Behavior

Sources are thread-safe.

## Actual Behavior

Several sources use variants of `if client == nil` inside the message handler function, which will race if two messages are handled concurrently.

AWSSQS source: https://github.com/knative/eventing-sources/blob/acb8625a4469cbf4969400e74ee98766d209e719/pkg/adapter/awssqs/adapter.go#L158

CronJob source: https://github.com/knative/eventing-sources/blob/acb8625a4469cbf4969400e74ee98766d209e719/pkg/adapter/cronjobevents/adapter.go#L71

GitHub source: https://github.com/knative/eventing-sources/blob/acb8625a4469cbf4969400e74ee98766d209e719/pkg/adapter/github/adapter.go#L58

## Additional Info

These client instantiations should either happen outside the message handler or they should be wrapped in a `sync.Once` (https://golang.org/pkg/sync/#Once).

/cc @n3wscott

### PR DESCRIPTION
**Pull request by whynowy**
Fixes #227 #206 

## Proposed Changes

  * Move client init out of PostMessage for Cronjob and AwsSqs sources
  * Use sync.Once to init client for github event source 
 

**Release Note**
No
```release-note
```

### CODE REVIEW

File: pkg/adapter/awssqs/adapter_test.go [hunk 1]
```diff
@@ -59,6 +59,11 @@ func TestPostMessage_ServeHTTP(t *testing.T) {
 				OnFailedPollWaitSecs: 1,
 			}
 
+			err := a.initClient()
```
Comment (evankanderson) [inline pkg/adapter/awssqs/adapter_test.go]: Slight preference for the 1-line format:

```golang
if err := a.initClient(); err != nil {
    t.Errorf("....")
}
```

Note that this changes the scope off `err` to be only within the `if` block, which should be harmless here, but does sometimes mean you can't use this format.

File: pkg/adapter/cronjobevents/adapter.go [hunk 2]
```diff
@@ -49,6 +49,22 @@ type Adapter struct {
 	client client.Client
 }
 
+// Initialize cloudevent client
+func (a *Adapter) initClient() error {
+	if a.client == nil {
+		var err error
+		if a.client, err = client.NewHTTPClient(
```
Comment (evankanderson) [inline pkg/adapter/cronjobevents/adapter.go]: In this case, I think it would be more fluent to do the opposite:

```golang
a.client, err := client.NewHTTPClient(
      ....
      ....)
if err != nil {
    return err
}
```

Two rubrics for choosing between the two forms:

1. Avoid the inline `if` assignment if the function call is multiple lines; it's harder to follow the `if` block that way.
2. Which is fewer lines of code? In this case, needing to pre-declare `var err error` in order to be able to assign to `a.client` removes all the benefit of inlining the assignment in the `if` statement.

File: pkg/adapter/github/adapter.go [hunk 3]
```diff
@@ -56,15 +59,20 @@ func (ra *Adapter) HandleEvent(payload interface{}, header webhooks.Header) {
...
+				client.WithTarget(ra.Sink),
+				client.WithHTTPBinaryEncoding(),
+				client.WithUUIDs(),
+				client.WithTimeNow(),
+			); err != nil {
+				log.Printf("failed to create cloudevent client: %s", err)
+			}
+		})
+	}
+	if ra.client == nil {
```
Comment (evankanderson) [inline pkg/adapter/github/adapter.go]: This double-check on `ra.client` is a bit strange. (I realize that the current structure requires this with `sync.Once`. Maybe extract this into a function, or call the `sync.Once` unconditionally?)

File: pkg/adapter/github/adapter.go [hunk 4]
```diff
@@ -56,15 +59,20 @@ func (ra *Adapter) HandleEvent(payload interface{}, header webhooks.Header) {
 
 func (ra *Adapter) handleEvent(payload interface{}, hdr http.Header) error {
 	if ra.client == nil {
```
Comment (grantr) [inline pkg/adapter/github/adapter.go]: nit: no need for this outer if.

```go
func (ra *Adapter) handleEvent(payload interface{}, hdr http.Header) error {
  ra.initClientOnce.Do(func() {
    // ...
  })
  if ra.client == nil {
  // ...
```

**Comment by grantr** [comment]
/hold
for @evankanderson's comments

File: pkg/adapter/github/adapter.go (hunk 3 above)
Comment (grantr) [reply pkg/adapter/github/adapter.go]: I think calling `once.Do()` every time is the right answer. https://github.com/knative/eventing-sources/pull/240#discussion_r264792991

File: pkg/adapter/cronjobevents/adapter.go (hunk 2 above)
Comment (whynowy) [reply pkg/adapter/cronjobevents/adapter.go]: @evankanderson - current golang doesn't support `a.client, err := client.NewHTTPClient....`

see the issue: 
https://github.com/golang/go/issues/30318

File: pkg/adapter/github/adapter.go (hunk 3 above)
Comment (whynowy) [reply pkg/adapter/github/adapter.go]: That is something I'm not very comfortable to use `Sync.once`, it can not do error handling and retry well. If it fails, `ra.client` will always be `nil` without any chance to retry. Anyways, I removed the check based on your comments.

Comment (grantr) [reply pkg/adapter/github/adapter.go]: That seems like a good reason to have an initialization method (like the `Start` method the other adapters have) so the caller can receive an error when the client is unable to start.

File: pkg/adapter/cronjobevents/adapter.go (hunk 2 above)
Comment (whynowy) [reply pkg/adapter/cronjobevents/adapter.go]: and this:  https://github.com/golang/go/issues/6842

File: pkg/adapter/github/adapter.go (hunk 3 above)
Comment (whynowy) [reply pkg/adapter/github/adapter.go]: In this case we need to make the initialization method public, and call it in `main.go` like below, it doesn't seem like very good. Is there any other way to do it?

```
	ra := &github.Adapter{
		Sink: *sink,
	}

        # Init cloud event client
        InitCloudEventClient()

	hook := gh.New(&gh.Config{Secret: secretToken})
	hook.RegisterEvents(ra.HandleEvent,
		gh.CommitCommentEvent,
```

Comment (grantr) [reply pkg/adapter/github/adapter.go]: Could all this be wrapped up in a blocking `Start`? But this seems like something to open an issue about rather than blocking the PR on it.

File: pkg/adapter/github/adapter.go [hunk 5]
```diff
@@ -71,9 +71,6 @@ func (ra *Adapter) handleEvent(payload interface{}, hdr http.Header) error {
 			}
 		})
 	}
-	if ra.client == nil {
-		return fmt.Errorf("failed to create cloudevent client")
-	}
```
Comment (grantr) [inline pkg/adapter/github/adapter.go]: I think I was expecting this second `if ra.client == nil` to remain, but remove the first `if ra.client == nil` around `ra.initClientOnce.Do()`.

Comment (grantr) [reply pkg/adapter/github/adapter.go]: Is that what you expected @evankanderson?

Comment (whynowy) [reply pkg/adapter/github/adapter.go]: 👍 Makes sense, It's better! I'll update it first :)
