### PR TITLE
Stop making sensitive kafka information available for logging

### LINKED ISSUE #328: stop logging user information, raw messages in Kafka event-source
## Expected Behavior
Setting up the kafka event-source shouldn't leak user/password combinations as well as log actual message contents (imagine if that was sensitive content) outside of the intended sink.  General configuration and metadata makes sense to log.

## Actual Behavior
Running through the Apache Kafka [README](https://github.com/knative/eventing-sources/blob/master/contrib/kafka/samples/README.md) shows log files that display from the event-source:

`{"level":"info","ts":"2019-03-19T22:31:52.689Z","caller":"receive_adapter/main.go:97","msg":"Starting Apache Kafka Receive Adapter...","adapter":{"BootstrapServers":"...","Topic":"...","ConsumerGroup":"...","Net":{"SASL" {"Enable":true,"User":"...","Password":"..."},"TLS":{"Enable":true}},"SinkURI":"http://event-display.default.svc.cluster.local/"}}`

Likewise, later, the README shows logging of the actual messages themselves:
`{"level":"info","ts":1553034726.5351956,"logger":"fallback","caller":"adapter/adapter.go:121","msg":"Received: {value 15 0 {\"msg\": \"This is a test!\"} <nil>}"}`

This is due to logging mechanism in the receive_adapter using reflection to print out the entire adapter struct, and then again in the adapter itself, printing out the message.

## Steps to Reproduce the Problem

  1. Follow steps specified in the Apache Kafka README
  2.
  3.

## Additional Info

### PR DESCRIPTION
**Pull request by lberk**
The adapter currently logs the kafka message directly to the console
instead; log metadata such as partition, topic, offset instead
The receive adapter is currently even worse due to the zap logging
done by reflection.  This prints out every struct parameter including
user/password combo.  Drop that and log less sensitive metadata.

Fixes #328

## Proposed Changes

  * Alter receive_adapter to print out a predefined set of field instead of reflecting the entire adapter struct
  * Change the adapter itself to log metadata only (partition, topic, offset)
  * Update the README to match the updated output

### CODE REVIEW

File: contrib/kafka/cmd/receive_adapter/main.go [hunk 1]
```diff
@@ -94,7 +94,12 @@ func main() {
 
 	stopCh := signals.SetupSignalHandler()
 
-	logger.Info("Starting Apache Kafka Receive Adapter...", zap.Reflect("adapter", adapter))
+	logger.Info("Starting Apache Kafka Receive Adapter...",
+		zap.String("Bootstrap Server", string(adapter.BootstrapServers)),
+		zap.String("Topics", string(adapter.Topics)),
+		zap.String("ConsumerGroup", string(adapter.ConsumerGroup)),
+		zap.String("SinkURI", string(adapter.SinkURI)),
+		zap.Bool("TLS", adapter.Net.SASL.Enable))
```
Comment (matzew) [inline contrib/kafka/cmd/receive_adapter/main.go]: :+1: nice find!

File: contrib/kafka/pkg/adapter/adapter.go [hunk 2]
```diff
@@ -77,8 +77,9 @@ func (a *Adapter) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.Co
 	logger := logging.FromContext(context.TODO())
 
 	for msg := range claim.Messages() {
-		logger.Info("Received: ", zap.Any("value", string(msg.Value)))
-
+		logger.Info("Received: ", zap.String("topic", string(msg.Topic)),
+			zap.Int("partition", int(msg.Partition)),
+			zap.Int("offset:", int(msg.Offset)))
```
Comment (matzew) [inline contrib/kafka/pkg/adapter/adapter.go]: minor:
`offset:` ends with a `:`  - should have the same for `topic` and `partition` ?

File: contrib/kafka/samples/README.md [hunk 3]
```diff
@@ -103,7 +103,7 @@ and an Event Display Service.
    configuration.
    ```
    $ kubectl logs kafka-source-xlnhq-5544766765-dnl5s
-   {"level":"info","ts":"2019-03-19T22:31:52.689Z","caller":"receive_adapter/main.go:97","msg":"Starting Apache Kafka Receive Adapter...","adapter":{"BootstrapServers":"...","Topic":"...","ConsumerGroup":"...","Net":{"SASL":{"Enable":true,"User":"...","Password":"..."},"TLS":{"Enable":true}},"SinkURI":"http://event-display.default.svc.cluster.local/"}}
+   {"level":"info","ts":"2019-04-01T19:09:32.164Z","caller":"receive_adapter/main.go:97","msg":"Starting Apache Kafka Receive Adapter...","Bootstrap Server":"...","Topics":".","ConsumerGroup":"...","SinkURI":"http://event-display.default.svc.cluster.local/","TLS":false}
```
Comment (matzew) [inline contrib/kafka/samples/README.md]: :+1:

**Comment by matzew** [comment]
@evankanderson @grantr given that the current IMPL logs sensible data, I'd recommend getting this into 0.5  branch/tag

File: contrib/kafka/pkg/adapter/adapter.go (hunk 2 above)
Comment (lberk) [reply contrib/kafka/pkg/adapter/adapter.go]: Ah, nice catch.  Thanks for the review, I've pushed a commit that fixes this and updates the README accordingly!

Comment (grantr) [reply contrib/kafka/pkg/adapter/adapter.go]: These should be `topic`, `partition`, and `offset`. No need for the `:` separator - zap's formatter will take care of that.

File: contrib/kafka/cmd/receive_adapter/main.go [hunk 4]
```diff
@@ -94,7 +94,12 @@ func main() {
 
 	stopCh := signals.SetupSignalHandler()
 
-	logger.Info("Starting Apache Kafka Receive Adapter...", zap.Reflect("adapter", adapter))
+	logger.Info("Starting Apache Kafka Receive Adapter...",
+		zap.String("Bootstrap Server", string(adapter.BootstrapServers)),
```
Comment (grantr) [inline contrib/kafka/cmd/receive_adapter/main.go]: Remove the space here. That makes the field names easier to use in search queries.

@yanweiguo do you have any guidance on casing for field names in logs? Should this be `BootstrapServer`, `bootstrapServer`, or `bootstrap_server`? I think I prefer `bootstrapServer` or `bootstrap_server`.

File: contrib/kafka/pkg/adapter/adapter.go [hunk 5]
```diff
@@ -77,8 +77,9 @@ func (a *Adapter) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.Co
 	logger := logging.FromContext(context.TODO())
 
 	for msg := range claim.Messages() {
-		logger.Info("Received: ", zap.Any("value", string(msg.Value)))
-
+		logger.Info("Received: ", zap.String("topic:", string(msg.Topic)),
```
Comment (grantr) [inline contrib/kafka/pkg/adapter/adapter.go]: No need for the casts here. `msg.Topic`, `msg.Partition`, and `msg.Offset` are already the expected types.

Comment (grantr) [inline contrib/kafka/pkg/adapter/adapter.go]: I think this should be `Debug` logging. Logging every message at `Info` can cause performance issues at high throughput.

File: contrib/kafka/samples/README.md [hunk 6]
```diff
@@ -117,7 +117,7 @@ and an Event Display Service.
    ```
    $ kubectl logs kafka-source-xlnhq-5544766765-dnl5s
    ...
-   {"level":"info","ts":1553034726.5351956,"logger":"fallback","caller":"adapter/adapter.go:121","msg":"Received: {value 15 0 {\"msg\": \"This is a test!\"} <nil>}"}
+   {"level":"info","ts":1554145778.9344022,"logger":"fallback","caller":"adapter/adapter.go:80","msg":"Received: {topic: 15 0 ... <nil>} {partition: 11 2  <nil>} {offset: 11 0  <nil>}"}
```
Comment (grantr) [inline contrib/kafka/samples/README.md]: Is this what the log messages look like? I wouldn't expect go structs to be logged here, given the log call at https://github.com/knative/eventing-sources/pull/329/files#diff-ca72cd4e88c155c7eabbb1bbd3d55b2fR80.

I'd expect something like this:

```
{"level":"info","ts":1554145778.9344022,"logger":"fallback","caller":"adapter/adapter.go:80",
"msg":"Received","topic":"mytopic","partition":11,"offset":151}
```

File: contrib/kafka/cmd/receive_adapter/main.go (hunk 4 above)
Comment (lberk) [reply contrib/kafka/cmd/receive_adapter/main.go]: I'll use your suggested bootstrapServer for now (also keeping relatively inline with the conventions inside the receive_adapter) unless we have a more preferred logging convention specified elsewhere.

File: contrib/kafka/pkg/adapter/adapter.go (hunk 5 above)
Comment (lberk) [reply contrib/kafka/pkg/adapter/adapter.go]: Sure, addressed in upcoming commit

Comment (lberk) [reply contrib/kafka/pkg/adapter/adapter.go]: Ok, Partition variable are int32's and Offset is int64.  Would you consider it acceptable to use zap.Int32() and zap.Int64() for the respective variables instead of the cast?

Comment (grantr) [reply contrib/kafka/pkg/adapter/adapter.go]: Yep that's what I'd prefer!

File: contrib/kafka/cmd/receive_adapter/main.go (hunk 4 above)
Comment (lberk) [reply contrib/kafka/cmd/receive_adapter/main.go]: I'll also remove the casts here as well

Comment (matzew) [reply contrib/kafka/cmd/receive_adapter/main.go]: FWIW, the CCP, over in eventing repo, uses `bootstrap_servers` in the config map for config:

https://github.com/knative/eventing/blob/master/contrib/kafka/config/kafka.yaml#L111

Comment (yanweiguo) [reply contrib/kafka/cmd/receive_adapter/main.go]: [Here](https://github.com/knative/pkg/blob/master/logging/logkey/constants.go) are the log keys we are currently using in logs. I don't think we have a strict naming policy for logs currently. Personally I prefer `bootstrap_server`.

cc @mdemirhan

File: contrib/kafka/samples/README.md (hunk 6 above)
Comment (lberk) [reply contrib/kafka/samples/README.md]: Looked into this a bit now.  Yes, that's what the logs look like.  It appears that both prior logging messages and current ones are using the fallback logger (which is why we have the extra output).

Testing this quickly locally by commenting out the 
`logger := logging.FromContext(context.TODO())`
line and adding in
```
logger := zap.NewExample()
defer logger.Sync()
```
Seems to produce the logging format you describe.

May I suggest that, due to this being a preexisting issue, we leave it for another, more focused Issue/PR regarding the use of the fallback logger?

File: contrib/kafka/cmd/receive_adapter/main.go (hunk 4 above)
Comment (lberk) [reply contrib/kafka/cmd/receive_adapter/main.go]: Sure, changed to `bootstrap_server` in e5053ba

File: contrib/kafka/cmd/receive_adapter/main.go [hunk 7]
```diff
@@ -95,7 +95,7 @@ func main() {
 	stopCh := signals.SetupSignalHandler()
 
 	logger.Info("Starting Apache Kafka Receive Adapter...",
-		zap.String("bootstrapServer", adapter.BootstrapServers),
+		zap.String("bootstrap_server", adapter.BootstrapServers),
```
Comment (aslom) [inline contrib/kafka/cmd/receive_adapter/main.go]: Underlying yaml parameter name is `bootstrapServers` (see it is plural with "s" at the end) I think it would be good to keep it consistent for people that will search in logs when troubleshooting?
https://github.com/knative/eventing-sources/blob/master/contrib/kafka/config/300-kafkasource.yaml#L46

File: contrib/kafka/cmd/receive_adapter/main.go [hunk 8]
```diff
@@ -95,7 +95,7 @@ func main() {
...
 		zap.String("Topics", adapter.Topics),
 		zap.String("ConsumerGroup", adapter.ConsumerGroup),
```
Comment (aslom) [inline contrib/kafka/cmd/receive_adapter/main.go]: Similarly I would keep the names of parameters exactly the same as far as capitalization goes: `topics`, `consumerGroup` etc.

```
		zap.String("consumerGroup", adapter.ConsumerGroup),
```

File: contrib/kafka/cmd/receive_adapter/main.go (hunk 7 above)
Comment (lberk) [reply contrib/kafka/cmd/receive_adapter/main.go]: This was already discussed here: https://github.com/knative/eventing-sources/pull/329#discussion_r271031783

File: contrib/kafka/cmd/receive_adapter/main.go (hunk 8 above)
Comment (lberk) [reply contrib/kafka/cmd/receive_adapter/main.go]: This was already discussed: https://github.com/knative/eventing-sources/pull/329#discussion_r271031783

File: contrib/kafka/samples/README.md (hunk 6 above)
Comment (grantr) [reply contrib/kafka/samples/README.md]: Sure, I created #332.
